development:
  password: shptka_f4085c231a6e22fd162305cf9c8056f6
  # theme_id: "127328813227" Dawn (Live theme)
  # Below is theme "Copy of Dawn"
  theme_id: "127466242219"
  store: usamas-imaginary-store.myshopify.com
